name: Upload File from Airtable
on:
  schedule:
    - cron: '0 0 * * *'  # Se ejecuta todos los días a las 00:00 UTC
  workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo
  
jobs:
  upload-file:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar el entorno
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Descargar archivo desde Airtable
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: |
          ATTACHMENT_URL=$(curl -s -X GET "https://api.airtable.com/v0/appAYimbUheznQQOk/Arxius_Galileu" \
            -H "Authorization: Bearer $AIRTABLE_API_KEY" \
            | jq -r '.records[0].fields.Arxiu[0].url')
          
          if [ -n "$ATTACHMENT_URL" ]; then
            curl -L -o file.xlsx "$ATTACHMENT_URL"
          else
            echo "No se encontró la URL del archivo"
            exit 1
          fi

      - name: Subir archivo al repositorio
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git clone "https://$GITHUB_TOKEN@github.com/perot84/galileu_to_airtable.git" repo
          cp file.xlsx repo/
          cd repo
          
          git add file.xlsx
          git commit -m "Actualización diaria del archivo desde Airtable" || exit 0
          git push origin main
