name: Sync Airtable with XLSX

on:
  push:
    paths:
      - 'xlsx/file.xlsx'
  workflow_dispatch:  # Permite ejecutar el workflow manualmente si es necesario

jobs:
  process-xlsx:
    runs-on: ubuntu-latest
    
    # Añadimos una condición para verificar si el archivo existe
    if: hashFiles('xlsx/file.xlsx') != ''

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Airtable Sync Script
        run: |
          python scripts/script.py
        env:
          # Podemos añadir variables de entorno si son necesarias
          FILE_PATH: 'xlsx/file.xlsx'
